min_version = "2024.9.5"

[env]
# Go to ref of this `ExamFactory.from_storage` still not working
# PYTHONPATH = "{{config_root}}/libs/examcore/src:{{config_root}}/backend/src:{{config_root}}/ml/src"
_.python.venv = { path = ".venv", create = true }

[tools]
python = "3.10"
